### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by AlexSkrypnyk** [beetboxvm/beetbox#133]
It has been discussed multiple times, but there is still no tangible result.

This issue is a placeholder for all logo discussions.

**Comment by BrianGilbert** [comment]
[beetbox-p.pdf](https://github.com/drupalmel/beetbox/files/131916/beetbox-p.pdf)

Here is the initially supplied artwork, I'm inviting Luis here so that the feedback can be collaborative.

I'm sure you all will anyway, but please keep the feedback respectful and positive.

Here is the initial brief I supplied him (if things have now moved on the most valuable thing we could do is refine the brief):

```
Also there is a community project called Beatbox that is looking for a logo https://github.com/drupalmel/beetbox

It is a Vagrant setup for doing Drupal development.
Some ideas for the logo:
-A druplicon that is a beetroot (perhaps an upside down beetroot as it already has the shape of a druplicon pretty much_
--https://spiritstate.files.wordpress.com/2014/01/beetroot1.jpg
-A druplicon made out of stacked slices of beetroot, something like the at&t logo
--https://upload.wikimedia.org/wikipedia/en/thumb/3/3a/AT%26T_logo_(horizontal).svg/1280px-AT%26T_logo_(horizontal).svg.png

```

**Comment by Decipher** [comment]
There's already a doc created in the shared for this feedback: https://drive.google.com/folderview?id=0BxnK2xzHmqN8alZiUWtXN3BSMnM&usp=sharing

**Comment by thom8** [comment]
Apart from the star I quite like this logo -- http://graphicriver.net/item/beetroot-studio-logo-template/6506280

**Comment by Lugasamo** [comment]
Hi Guys,

I did another proposal, let me know your thoughts.
![beetbox-v2](https://cloud.githubusercontent.com/assets/6549200/13302467/27773be2-db9e-11e5-8032-a013411cb364.gif)

**Comment by thom8** [comment]
Please reopen if there's any outstanding tasks relating to the logo.
