### ISSUE TITLE
Req: Way to add known remotes

### ISSUE THREAD

**Issue by BrianGilbert** [beetboxvm/beetbox#22]
so things like building a makefile that references a private repo can still build without erroring.

**Comment by Decipher** [comment]
This was already available in DMBox, so is likely still available.

**Comment by thom8** [comment]
Whilst possible, we should try to avoid needing to give the provisioner special access.
I would recommend using a local stub to build the profile which should have no dependencies on a private repo.

**Comment by Decipher** [comment]
Honestly, my preference is that the host machine does the build, not the
guest machines, making it a non issue.

**Comment by thom8** [comment]
Sure but this also means a CI environment can't build the site.

**Comment by Decipher** [comment]
True. In which case known hosts will be a requirement as we host on Gitlab
and CI would need to build from that host (for RLs workflow).  Will look
into this more when I'm back at work.

**Comment by thom8** [comment]
Would be nice to make these hosts configurable too -- https://github.com/thom8/packer-templates/blob/master/ubuntu-14.04-x86_64/scripts/vagrant.sh#L10 

This is to completely stop hostchecking rather than adding to known_hosts.

**Comment by Decipher** [comment]
That was actually what I had used previously, and why I had thought it was already in there previously, however I suppose the reason I used it previously was that we had built our own box rather than just customising the config.

I've done a quick search and come up with two possible existing roles to tackle that approach:
- https://github.com/gaqzi/ansible-ssh-config
- https://github.com/jdauphant/ansible-role-ssh-config

Haven't tested either yet, but will try to look into it today.

**Comment by thom8** [comment]
This issue has been addressed by the known-hosts role -- https://github.com/beetboxvm/beetbox/tree/master/provisioning/ansible/roles/beetbox-known-hosts/tasks

eg

```
known_hosts:
  - github.com
```

If there are any further requirements please reopen or create a new issue.
