### ISSUE TITLE
What to type into browser to start site

### ISSUE THREAD

**Issue by SamStamport** [beetboxvm/beetbox#278]
I've read the documentation, but can't seem to find what I type into my browser to access my site once it has been set up. 

Please advise.

Thanks!

**Comment by thom8** [comment]
If you have installed the requirements -- https://github.com/beetboxvm/beetbox#requirements

It will be the `beet_domain` variable in your `.beetbox/config.yml` file.

**Comment by SamStamport** [comment]
I'm pretty sure I installed all the requirements. 

beet_domain: cb.local

When I type "cb.local" into Chrome I get a Bing search results page. What am I doing wrong?

**Comment by thom8** [comment]
Can you try ping the domain? -- `ping cb.local`

If so you might need to use `http://cb.local` depending on the browser, cb.local is a domain rather than a URL.

If you can't ping it can you run `vagrant plugin list` and post the result, also what OS are you using?

**Comment by SamStamport** [comment]
Yea!

http://cb.local worked. I'm getting a SQL error, but that's because I've not yet copied the database.

PS C:\Users\samst\Desktop\Drupal\cb> ping cb.local

Pinging cb.local [fe80::a00:27ff:fe95:88d0%4] with 32 bytes of data:
Reply from fe80::a00:27ff:fe95:88d0%4: time<1ms 
Reply from fe80::a00:27ff:fe95:88d0%4: time<1ms 
Reply from fe80::a00:27ff:fe95:88d0%4: time<1ms 
Reply from fe80::a00:27ff:fe95:88d0%4: time<1ms 

Ping statistics for fe80::a00:27ff:fe95:88d0%4:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms

PS C:\Users\samst\Desktop\Drupal\cb> vagrant plugin list
vagrant-auto_network (1.0.2)
vagrant-hostsupdater (1.0.2)
vagrant-share (1.1.5, system)

I'm using Windows 10 and PowerShell with Administrative privileges to run vagrant.

What do I type into chrome to get to adminer or phpMyAdmin?

**Comment by ColumbiaBlooms** [comment]
Yea! http://cb.local worked.

PS C:\Users\samst\Desktop\Drupal\cb> ping cb.local

Pinging cb.local [fe80::a00:27ff:fe95:88d0%4] with 32 bytes of data:
Reply from fe80::a00:27ff:fe95:88d0%4: time<1ms 
Reply from fe80::a00:27ff:fe95:88d0%4: time<1ms 
Reply from fe80::a00:27ff:fe95:88d0%4: time<1ms 
Reply from fe80::a00:27ff:fe95:88d0%4: time<1ms 

Ping statistics for fe80::a00:27ff:fe95:88d0%4:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms

PS C:\Users\samst\Desktop\Drupal\cb> vagrant plugin list
vagrant-auto_network (1.0.2)
vagrant-hostsupdater (1.0.2)
vagrant-share (1.1.5, system)

I'm getting a SQL error, but that's because I've not copied the database into the VM. 

What do I type into Chrome to get to adminer or phpMyAdmin?

I'm running Win 10 using PowerShell to run vagrant commands.

**Comment by ColumbiaBlooms** [comment]
Yea! http://cb.local works.

I'm running Win 10 and using PowerShell running as administrator to run vagrant.

I'm getting a SQL error, but that's because I've not yet loaded the database. What do I type into Chrome to get to adminer or phpMyAdmin?

PS C:\Users\samst\Desktop\Drupal\cb> ping cb.local

Pinging cb.local [fe80::a00:27ff:fe95:88d0%4] with 32 bytes of data:
Reply from fe80::a00:27ff:fe95:88d0%4: time<1ms 
Reply from fe80::a00:27ff:fe95:88d0%4: time<1ms 
Reply from fe80::a00:27ff:fe95:88d0%4: time<1ms 
Reply from fe80::a00:27ff:fe95:88d0%4: time<1ms 

Ping statistics for fe80::a00:27ff:fe95:88d0%4:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms

PS C:\Users\samst\Desktop\Drupal\cb> vagrant plugin list
vagrant-auto_network (1.0.2)
vagrant-hostsupdater (1.0.2)
vagrant-share (1.1.5, system)

**Comment by thom8** [comment]
We do have adminer but you'd need to add a new vhost.

However it might be easier to treat it as a remote server and use a local SQL client on the host or use drush to import your database - `drush sql-cli < ~/db.sql`

**Comment by SamStamport** [comment]
Sorry for what is probably a dumb question ...

How do I run Drush? When I type "drush status" in PowerShell from the folder that I use to run Vagrant I get "The term 'drush' is not recognized". 

I searched http://beetbox.readthedocs.io/en/stable/ and did web searches, but found nothing.

I am a newbie and a one-man shop. I really want this to work so that I can get back to developing & supporting my Drupal site.

Thanks!

**Comment by Decipher** [comment]
Unfortunately the Windows Drush installer was discontinued, so your best option is probably to run `vagrant ssh` and run the drush commands from within Beetbox.

**Comment by SamStamport** [comment]
Oh my! I really would like Drush to work. I guess this means I'll have to figure out how to make DrupalVM work? It's my understanding that Drush is supported and works with DrupalVM?

When I type "vagrant ssh" I get "`ssh` executable not found in any directories in the %PATH% 
variable."

I really had hoped that DrupalVM or BeetBox would permanently solve my server problems. I'm trying to get my local site to mirror my remote in terms of the same versions of MySQL, PHP, etc. Bitnami installed without too much fuss, but I discovered that I cannot modify the versions of MySQL, PHP, etc.

**Comment by thom8** [comment]
@ColumbiaBlooms you can use drush on your host machine @Decipher was suggesting that it might be easier to do it inside the VM rather than battle with powershell...

http://docs.drush.org/en/master/install/

**Comment by thom8** [comment]
Also have a read of this - http://docs.drupalvm.com/en/latest/other/windows/

There's nothing specific to DrupalVM and the same applies to this project.

**Comment by SamStamport** [comment]
I've been down the Drush on Windows route before. I spent many days on this and finally discovered that commands are limited when installed on Windows.

@Decipher says to run "vagrant ssh" to get to Drush, but as you can see from my previous post I'm getting an error message.

**Comment by thom8** [comment]
@ColumbiaBlooms Windows doesn't support SSH by default...

I'd recommend something like http://cmder.net/

hopefully the bash support will help when it's generally available.

**Comment by SamStamport** [comment]
It looks like BeetBox will not meet my needs. I really, really want to use native Windows without having to install a lot of other stuff. Vagrant seems to hold this promise, but apparently BeetBox does not.

I really have high hopes for Vagrant that it will still work and give me an environment that I don't have to tinker with all the time if I can just wrap my brain around it and/or DrupalVM. I need a simple environment on my Win 10 machine with a fully functional Drush, shared folders, and the ability to easily change versions for PHP, MySQL, etc.

**Comment by thom8** [comment]
Sorry BeetBox is not designed to help with your host machine requirements, it's so your host machine only requires a minimal setup and everything else runs inside the VM.

However, I'd recommend getting SSH working for any Vagrant project.

**Comment by SamStamport** [comment]
Thanks for all your help and honesty. I'll go back to trying to learn DrupalVM and Vagrant. 

Please close this problem report.

**Comment by thom8** [comment]
No worries -- you'll still need SSH for DrupalVM, this project is almost identical it just uses a pre-provisioned base box -- https://github.com/beetboxvm/beetbox#beetbox---a-pre-provisioned-lmp-stack
