### ISSUE TITLE
Any reason phpunit is not added

### ISSUE THREAD

**Issue by lsolesen** [beetboxvm/beetbox#339]
I am ready to start hacking on my Beetbox. Just wondering why PHPUnit is not installed by default globally?

**Comment by thom8** [comment]
@lsolesen rather than relying on a preinstalled default version I'd recommend adding `phpunit` as a dependency of the project. 

This way you can set version constraints and the same version can be used in other environments.

Otherwise, you can easily configure a globally installed version for your own project with `composer_global_packages` in your `config.yml`

eg.

```
composer_global_packages:
  - name: phpunit/phpunit
    release: '5.5.*'
```
