### ISSUE TITLE
Please clarify advantages to drupalvm

### ISSUE THREAD

**Issue by mminklet** [beetboxvm/beetbox#350]
This post is not an intention to sh*t on beetbox. I've used it in a commercial setting and it's a good solution, and I appreciate the work you're doing. However, as someone looking to implement a solution as standard across our agency, I am still unclear on the advantage of beetbox over drupalvm, and your documentation is not clear. Can you please expand on the following points:

* You only add config to your project and don't need to manage a fork of the whole provisioning system.

You don’t need to do this with drupalvm, just use git submodules. Unless I'm misunderstanding?

* It uses a pre-provisioned base box so it’s much faster to provision.
Ok granted. But I haven't seen an advantage of this in a real world situation, it still takes a long time to provision.

* Each new version of the box gets published to Atlas only if all roles are provisioned making the box always stable.
Drupalvm releases are tested and stable, can you clarify what this means? Just purely that you don't have to install the ansible roles locally? 

* With linked clones each VM is a small clone of a single master.
Linked clones is a feature of vagrant, so therefore inherently built into drupalvm, isn't it?

* You can reuse the same provisioning system for a CI environment.
You can do that that with drupalvm? Please expand

* Minimal host machine dependencies.
Which dependency? Ansible?

In fact I've actually found beetbox harder to configure because the documentation is lacking compared to drupalvm.

Essentially, I don't see the advantage to using beetbox over drupalvm when considering the open source project support, which is a large factor. I'd love to be convinced otherwise, again I'm not trying to disparage beetbox, but as a user and someone owning this space for the business, this is my view.

**Comment by thom8** [comment]
@MichaelMallett first off thanks for raising this issue, I'll try to address each point :

> You only add config to your project and don't need to manage a fork of the whole provisioning system.

This advantage is slightly dated as DVM has since implemented integrations options including submodules and composer package however there's more maintenance overhead eg. https://github.com/srowlands/govcms-devkit (This branch is 60 commits ahead, 634 commits behind geerlingguy:master.)

> It uses a pre-provisioned base box so it’s much faster to provision.

There's no doubt that a pre-provisioned base box speeds up provisioning time but linked clones also decreases the "per project" VM size as each project is only as big as the changes made to the base box.

> Each new version of the box gets published to Atlas only if all roles are provisioned making the box always stable.

DVM requires building an unprovisioned base box each time, therefore any issues during provisioning are evident, in beetbox the majority of provisioning task are completed during the initial build and therefore skipped during a "reprovision".

> With linked clones each VM is a small clone of a single master.

Correct this has been available in DVM for some time however a clone of an unprovisioned/semi provisioned base box means the per box size is bigger as it will contain all provisioning changes rather than the changes to the base box of beetbox.

> You can reuse the same provisioning system for a CI environment.

As beetbox has a predefined OS and build script you can reuse the project CI build for your own project see -- http://beetbox.readthedocs.io/en/latest/continuous-integration/circle-ci/
This is a generic `circle.yml` file that will rebuild your beetbox environment in circle CI, from this point you can run tests, we realise this approach is quite time consuming so would recommend using a "pre provisioned" docker image -- https://hub.docker.com/u/beet/
*note this is an advanced use case.

> Minimal host machine dependencies.

Sure there's not many dependencies with DVM but this ensures the correct version will work, we can plan upgrade to ansible and confirm support before pushing a new release.

> In fact I've actually found beetbox harder to configure because the documentation is lacking compared to drupalvm.

Beetbox is a pre-provisioned version of drupalvm, so in most cases documentation is the same.. It would be nice to link directly to DVM docs so we don't need to duplicate efforts here.

---

beetbox was originally developed for a project using a very strict feature branch policy so each branch needed a completely clean build to test deployability and if you're rebuilding multiple times a day you'd do anything to speed up provisioning time.. this was greatly improved with [multidev](https://github.com/thom8/beetbox/tree/multidev) essentially having a VM per branch. Again another very advanced use case but more feasible with beetbox...

The project has also been forked as used for non L*MP stacks so it can also be forked and used internally if required..

I'd love to push some of this work back upstream but understand the constraints with OS support etc, perhaps it can be discussed further here -- https://github.com/geerlingguy/drupal-vm/issues/996

At the end of the day, if you don't have any direct benefits for your use case I'd highly recommend DVM ;)

thanks @geerlingguy!

**Comment by geerlingguy** [comment]
Nice, comprehensive overview! To me, one of the main benefits of a downstream project like Beetbox is speed/efficiency—I'm also looking long-term at how Drupal VM can itself be better in this regard... or how we can make it easier/faster/simpler for downstream projects like Beetbox to get better, and some thoughts are already outlined here: https://github.com/geerlingguy/drupal-vm/issues/996 (as @thom8 mentioned).

Someday I'll get to meet @thom8 in person and thank him for his work :D

**Comment by mminklet** [comment]
Thanks @thom8 that's really useful info

**Comment by fubarhouse** [comment]
I'm subscribing - this is a rather useful comparison.
Thanks @thom8.

**Comment by AlexSkrypnyk** [comment]
> It uses a pre-provisioned base box so it’s much faster to provision.
> Ok granted. But I haven't seen an advantage of this in a real world situation, it still takes a long time to provision.

As one of the earliest adopters of *beetbox* and someone who used `PuPHPet` and `phansible` before, the fact that a box comes pre-provisioned is the most important advantage of *beetbox*. There are 2 main points:
1. Updating the box will *always* give you a box that is stable enough. You will never have a situation like PuPHPet projects had, where you starting the update, box is destroyed, and a build for a new box fails because of some dependency issues and all work just stops until dependencies issues are resolved. I can't stress enough how bad it is to be paralised by something that you were not even intended to work on and now have to fix.
2. Beetbox have very sensible defaults: the box is available within 4-5 minutes after `vagrant up` with the whole stack ready to go. So it does not actually take a long time to provision. Yes, it is longer then MAMP, but the persistence of configuration between machines within a dev team and fully isolated stack worth the wait.

**Comment by mminklet** [comment]
Hello @alexdesignworks , nice to see you again.

Sorry, I'm really not talking about MAMP! I'm talking about the advantages over drupalvm specifically. I know the advantages of an isolated solution, that's why I'm trying to implement it across the team.

I'm just going to set up both and see which one we prefer, and follow up with our findings.

**Comment by AlexSkrypnyk** [comment]
@thom8 Should we convert your [answer](https://github.com/beetboxvm/beetbox/issues/350#issuecomment-261521470) to some kind of FAQ in docs?

**Comment by thom8** [comment]
@alexdesignworks yeah it could be on it own page with a link from the simplified FAQ

**Comment by thom8** [comment]
@MichaelMallett interested to know how you got on, it seems the projects are converging a lot more now so its mainly the `pre-provisioning` which is the major difference.

I personally still like being able to do a full rebuild `vagrant destroy -f && vagrant up` in "less than 3 mins", so I'll often rebuild about once a day, _I don't treat my VM's very well_ ;)

We currently use a custom playbook -- https://github.com/beetboxvm/beetbox/blob/master/docs/configuration/ansible/custom-playbook.md

so it's very stripped down to only configure specific overrides for the project.

Anyways, will continue to try push features back upstream to DVM where appropriate.

**Comment by mminklet** [comment]
Hey Thom,

I've had to hold off on this for the last few months I think, but thanks
for the additional info. I'm hoping to get some time to pick this back up
again and I'll be back in touch then.

**Comment by thom8** [comment]
@MichaelMallett no worries, will close this for now.
