### ISSUE TITLE
Automated builds

### ISSUE THREAD

**Issue by Decipher** [beetboxvm/beetbox#43]
Currently it's up to either @thom8 or myself to trigger a new build of the base box, so ideally we should set up some automation.

My thoughts are:
- Nightly or per master commit builds to a alternate namespace (beetbox-dev)
- Release/Tag based builds to the primary namespace (beetbox)

Both of these could potentially be triggered from Circle CI accordingly.

**Comment by thom8** [comment]
I recommend that we use tags on the repo to trigger circle CI to create a new build on atlas.

https://circleci.com/docs/configuration#tags

This way the project tags are directly linked to the base box versions.

**Comment by Decipher** [comment]
On this, it occurred to me a while back that we should probably change the versioning pattern when we do this

Currently the numbering is: `0.1.[BUILD]`
I propose we change to: `X.Y.Z-b[BUILD]` or similar, which should become: `[TAG]-b[BUILD]`

That way, if we tag `1.0.0` but the build fails due to an anomaly (apt repo's inaccessible) we can just re-trigger a new build on Atlas without having to re-tag another commit or having the built version mis-match the tag.

**Comment by thom8** [comment]
With this change we should update the altas version to use the same tag version rather than the build number -- https://github.com/thom8/packer-templates/blob/master/ubuntu-14.04-x86_64/template.json#L3

If the build fails for any reason another build can be triggered and it will build the tagged version.

This tag can be passed directly to atlas as an arg of `packer push`

**Comment by thom8** [comment]
Fixed in #81 & #82
