### ISSUE TITLE
Global, system-wide defaults

### ISSUE THREAD

**Issue by klonos** [beetboxvm/beetbox#433]
## Problem/Motivation

It is not clear to me from the documentation how one can set system-wide defaults (for example php version), or if that is possible at all to begin with. So this is a documentation question/feature request.

## Expected behaviour

Being able to specify per-user default config that for example sets the php version of newly provisioned boxes to 5.6 by default (unless specifically overwritten by per-box settings).

## Actual behaviour

In latest versions of beetbox, php 7.1 is the default and it is tedious for one to have to repeatedly overwrite this setting for every new box.

## Steps to reproduce

Fire up a new box. The default php version is 7.1, but it seems that still [more than 90% of the market uses some version of 5.x](https://w3techs.com/technologies/details/pl-php/all/all). Chances are that most devs will be configuring their local boxes to use 5.x in order to match their prod, so it should be made easy to be able to override the default in a system-wide level.

## Proposed changes

Allow for a beetbox.default.config or something like that lives somewhere under each user's profile. Anything set in that config should override the defaults whatever these may be with each new version of beetbox.

**Comment by thom8** [comment]
@klonos this is already available as described here -- http://beetbox.readthedocs.io/en/stable/configuration/ansible/global-config/

However, I'd strongly suggest you don't rely on this for things like the `php_version` as when someone else builds the project it won't work unless they complete this manual step.

The global config was intended for a developer's personal config preferences rather than project dependencies.
