### ISSUE TITLE
box 'beet/box' could not be found

### ISSUE THREAD

**Issue by kostajh** [beetboxvm/beetbox#468]
## Problem/Motivation

```
11:18 $ vagrant up
Bringing machine 'beetbox' up with 'virtualbox' provider...
==> beetbox: Box 'beet/box' could not be found. Attempting to find and install...
    beetbox: Box Provider: virtualbox
    beetbox: Box Version: ~> 0.8.0
The box 'beet/box' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/beet/box"]
Error: The requested URL returned error: 404 Not Found
```

## Expected behaviour

To find the box

## Actual behaviour

404

## Steps to reproduce

Follow the quickstart instructions for `composer require` and `vagrant up`.

n.b. I'm on a train now, so perhaps the poor wifi is coming into play, but it seems like a larger issue as https://atlas.hashicorp.com/beet/box redirects to https://app.terraform.io/beet/box which shows a 404.

## Proposed changes

> (If you have a proposed change, workaround or fix, describe the rationale behind it)

**Comment by rwitchell** [comment]
Hi @kostajh ,

the beetbox file is pulled from hashicorp's servers (creators of Vagrant). Hashicorp updated their storage URL from `atlas.hashicorp.com` to `vagrantcloud.com` and (i'm guessing: ...) disabled/turned off the old site. This error is occurring for you because you still have vagrant 1.x running on your machine, instead of the latest vagrant 2.x (vagrant 1.x is still good for LTS reasons - no need to upgrade yet)

Instead of upgrading to vagrant 2.x, you can to go to the location of your vagrant boxes, find the `metadate_url` file in the beetboxvm folder, open it, and change the URL there.

a `vagrant box update` or `vagrant up` will then work correctly.

read more here: https://github.com/hashicorp/vagrant/issues/9442

**Comment by kostajh** [comment]
Got it, thanks @rwitchell!
